#!/usr/bin/env python
import sys
from ecl import EclDataType
from ecl.eclfile import EclFile
from ecl.grid import EclGrid, EclRegion

# This small script will load a unified restart file and a grid and create a
# EclKW instance with the pressure change for the entire simulation. It will
# then create a EclRegion and select all the cells where the pressure has
# increased and create an integer indicator field - PINC - with all the cells
# which have experienced a pressure increase.



def main(grid, rst_file, num_points, csv_file):
    pressure_list = rst_file["PRESSURE"]
    initial_pressure = pressure_list[0]
    final_pressure = pressure_list[-1]
    dp = abs(final_pressure - initial_pressure)

    region = EclRegion(grid, False)
    region.select_more(dp, 0)
    pinc = EclKW("PINC", grid.get_global_size(), EclDataType.ECL_INT)
    pinc.assign(0)
    pinc.assign(1, mask = region)
    with open("pinc.grdecl", "w") as f:
        pinc.write_grdecl(f)



if __name__ == "__main__":
    case = sys.argv[1]
    grid = EclGrid("{}.EGRID".format(case))
    rst_file = EclFile("{}.UNRST".format(case))

    frame = main(grid, rst_file, options.num, options.output)
