#!/usr/bin/env python
import sys
import argparse
import pandas as pd
import numpy as np
from ecl.eclfile import EclFile
from ecl.grid import EclGrid
from ecl.well import WellInfo

# This little script will load a restart file and a grid, it will go through
# all the wells defined in the restart file, and for each well it will iterate
# through all the connections and determine the minimum and maximum pressure
# throughout the entire simulation.

def well_report(well_state, pressure_list, grid):
    first_conn = True
    for conn in well_state.globalConnections():
        plist = []
        for p in pressure_list:
            plist.append( p[grid.get_active_index(ijk=conn.ijk())] )

        max_pressure = max(plist)
        min_pressure = min(plist)

        if first_conn:
            well = well_state.name()
            first_conn = False
        else:
            well = ""
        print "{:8s}   {:15s}  {:5.0f}     {:5.0f}".format(well, conn.ijk(), min_pressure, max_pressure)



def main(grid, rst_file):
    well_info = WellInfo(grid, rst_file)
    pressure_list = rst_file["PRESSURE"]

    print "Well      Connection       min(P)    max(P)"
    print "==========================================="
    for well_ts in well_info:
        well_state = well_ts[0]
        well_report(well_state, pressure_list, grid)
        print


if __name__ == "__main__":
    case = sys.argv[1]
    grid = EclGrid("{}.EGRID".format(case))
    rst_file = EclFile("{}.UNRST".format(case))

    main(grid, rst_file)
